/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ejercicio12Cliente;

import Cartas.Cartas;
import java.io.ObjectInputStream;
import java.net.Socket;

/**
 *
 * @author faranzabe
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BT = new javax.swing.JButton();
        ET = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BT.setText("Púlsame");
        BT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTActionPerformed(evt);
            }
        });

        ET.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ETMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(BT))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(ET, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(135, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(ET, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BT)
                .addGap(59, 59, 59))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTActionPerformed
        cambia_carta();
    }//GEN-LAST:event_BTActionPerformed

    private void ETMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ETMouseClicked
        cambia_carta();
    }//GEN-LAST:event_ETMouseClicked

    private void cambia_carta(){
        String ruta;
        try{
            /* Se crea el socket cliente */
            Socket servidor = new Socket ("localhost", 35557);
            //System.out.println ("conectado");

            /* Se obtiene un stream de lectura para leer objetos */
            ObjectInputStream bufferObjetos = new ObjectInputStream (servidor.getInputStream());

            /* Se lee un Datosocket que nos env�a el servidor y se muestra 
            * en pantalla */
            Cartas carta = (Cartas)bufferObjetos.readObject();
            System.out.println(carta.toString());
            ruta=carta.getRuta();
        
            
            ET.setIcon(new javax.swing.ImageIcon(getClass().getResource(ruta)));
   
    }catch(Exception e){
            System.out.println("Error en "+e);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BT;
    private javax.swing.JLabel ET;
    // End of variables declaration//GEN-END:variables
}
